# Generated by Django 3.1.2 on 2020-12-04 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registered',
            name='role',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
