# Generated by Django 3.1.2 on 2020-12-04 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_registered_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='camp_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camp_name', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=10)),
            ],
        ),
    ]
