# Generated by Django 3.1.2 on 2020-12-05 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_victim_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='requirement_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camp_name', models.CharField(max_length=250)),
                ('requirements_details', models.CharField(max_length=1000)),
            ],
        ),
    ]
