# Generated by Django 3.1.2 on 2020-12-05 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_requirement_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement_table',
            name='requirement_type',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
