# Generated by Django 3.1.2 on 2020-12-07 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_auto_20201205_1744'),
    ]

    operations = [
        migrations.CreateModel(
            name='warning_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=250)),
                ('message', models.CharField(max_length=250)),
            ],
        ),
    ]
