# Generated by Django 3.1.2 on 2020-12-08 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_requirement_table_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='vechile_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=250)),
                ('vechile_number', models.CharField(max_length=250)),
                ('vechile_type', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
    ]
