# Generated by Django 3.1.2 on 2020-12-08 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_vechile_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vechile_info',
            name='vechile_number',
        ),
    ]
