# Generated by Django 3.1.2 on 2020-12-08 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_remove_vechile_info_vechile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='registered',
            name='email',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registered',
            name='phone',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
