# Generated by Django 3.1.2 on 2020-12-08 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_auto_20201208_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='registered',
            name='name',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
