# Generated by Django 3.1.2 on 2020-12-08 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_registered_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='registered',
            name='status',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
