# Generated by Django 3.1.2 on 2020-12-08 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_registered_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='flood_area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=250)),
                ('map_location', models.CharField(max_length=1000)),
            ],
        ),
    ]
