# Generated by Django 3.1.2 on 2020-12-10 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_remove_login_table_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='victim_details',
            name='health_status',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
