# Generated by Django 3.1.6 on 2021-05-29 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0021_auto_20210529_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='stock',
            field=models.CharField(max_length=200),
        ),
    ]
