# Generated by Django 3.1.6 on 2021-05-29 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0022_auto_20210529_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
